config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'home/index'
  devise_for :users
  get 'users/show'
  get 'users/all'
  resources :opinion, only: [:index, :show, :create]
  post 'home/follow'
  post 'home/unfollow'
  root to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/following.rb
class Following < ApplicationRecord
  belongs_to :follower, foreign_key: :follower_id, class_name: 'User'
  belongs_to :followed, foreign_key: :followed_id, class_name: 'User'
end

app/models/opinion.rb
class Opinion < ApplicationRecord
  belongs_to :user, foreign_key: :author_id
  scope :desc, -> { order(created_at: :desc) }

  validates :text, presence: true, length: { minimum: 5, maximum: 1000 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  scope :desc, -> { order(created_at: :desc) }
  has_one_attached :Photo
  has_one_attached :CoverImage
  has_many :opinions, foreign_key: :author_id

  has_many :followers_connection, foreign_key: :followed_id, class_name: 'Following', dependent: :destroy
  has_many :followers, through: :followers_connection, source: :follower
  has_many :followed_connection, foreign_key: :follower_id, class_name: 'Following', dependent: :destroy
  has_many :followed, through: :followed_connection, source: :followed

  validates :user_name, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze }
  validates :full_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[user_name full_name])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[user_name full_name Photo CoverImage])
  end

  private

  # Overwriting the sign_out redirect path method
  def after_sign_out_path_for(_resource_or_scope)
    new_user_session_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :logged_in_user
  def index
    followers = current_user.followed.ids
    followers.push(current_user.id)
    suggested = User.where.not(id: followers).desc
    @who_to = []
    @who_to = if suggested.ids.count >= 4
                selected(suggested.to_a)
              else
                suggested
              end
    @opinion = Opinion.all.desc
  end

  def follow
    Following.create(follower_id: current_user.id, followed_id: allowed_params)
    redirect_to users_show_path('id' => allowed_params)
  end

  def unfollow
    f = Following.where(followed_id: allowed_params, follower_id: current_user.id)
    Following.delete(f)
    redirect_to users_show_path('id' => allowed_params)
  end

  private

  def allowed_params
    params.require(:id)
  end

  def logged_in_user
    redirect_to user_session_path unless signed_in?
  end

  def get_random(array)
    array.sample
  end

  def selected(array)
    new_array = []
    4.times do
      random_item = get_random(array)
      new_array.push(random_item)
      array.delete(random_item)
    end
    new_array
  end
end

app/controllers/opinion_controller.rb
class OpinionController < ApplicationController
  def new
    @opinion = Opinion.new
  end

  def create
    @opinion = current_user.opinions.new(opinion_params)
    if @opinion.save
      redirect_to root_path
    else
      flash.now[:alert] = 'minimum 5 and max 500 words are allowed'
      render 'new'
      flash[:alert] = 'minimum 5 and max 500 words are allowed'
    end
  end

  private

  def opinion_params
    params.require(:opinion).permit(:text)
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
    # def index
    #     @user = User.all
    # end
    # def show
    #     @user = User.find(params[:id])
    #     @opinion = @user.opinions.ordered_by_most_recent
    # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def all
    @user = User.all
  end
end

app/helpers/application_helper.rb
# rubocop:disable Layout/LineLength
module ApplicationHelper
  def check_dp(user)
    user.Photo.attached?
  end

  def get_name(id)
    u = User.find(id)
    u.user_name
  end

  def check_user_name(user)
    user_name = if user.full_name.nil? && user.user_name.nil?
                  'fake'
                elsif user.user_name.nil?
                  user.full_name
                else
                  user.user_name
                end
    user_name
  end

  def check_follower(user)
    follow = ''
    if user == current_user
      follow = (link_to '', users_show_path('id' => user.id), method: :post, class: 'fa fa-check-circle my-3').html_safe
    elsif map_followers(user) == true
      follow = (link_to '+', home_follow_path('id' => user.id), method: :post, class: 'font-wight-bold').html_safe
    elsif map_followers(user) == false
      follow = (link_to '-', home_unfollow_path('id' => user.id), method: :post, class: 'font-wight-bold mx-1').html_safe
    end
    follow
  end

  private

  def map_followers(user)
    get_ids = user.followers.map(&:id)
    check = if get_ids.include?(current_user.id)
              false
            else
              true
            end
    check
  end
end
# rubocop:enable Layout/LineLength

app/helpers/following_helper.rb
module FollowingHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/opinion_helper.rb
module OpinionHelper
end

app/helpers/user_helper.rb
module UserHelper
  def check_photo(user)
    (user.Photo.attached? && user.CoverImage.attached?)
  end
end

app/views/home/index.html.erb
<div class="d-flex flex-row no-hover">
    <div class="">
        <%= render 'shared/left-nav'%>
    </div>
    <main class="d-flex flex-column main">
        <div>
            <%= render 'shared/top-nav'%>
        </div>
        <div class="d-flex flex-column">
            <% if !check_photo(current_user) %>
            <div class=d-flex flex-column>
                <p class="text-primary ">Complete your profile</p>
                <%= link_to 'click here', edit_user_registration_path, class: "text-danger ml-1" %>
            </div>
            <% end %>
            <div class="main-content d-flex flex-row ">
                <div class="d-flex flex-column ">
                    <%= render 'shared/opinion'%>
                    <div class="feed-container p-2 ml-4">
                        <% @opinion.each do |o| %>
                            <h5 class="font-weight-bold"><%= get_name(o.author_id) %></h5>
                            <p><%= o.text %></p>
                        <% end %>
                    </div>
                </div>
                <div class="d-flex flex-column fixed-right">
                    <h5 class="text-center">Who to follow</h5>
                    <% @who_to.each do |f| %>
                        <%= render partial: 'shared/who-to', locals: {suggested_user: f}  %>
                    <% end %>
                </div>
            </div>
        </div>
    </main>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twitter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/opinion/new.html.erb
<%= render 'shared/opinion'%>

app/views/shared/_opinion.html.erb
<div class="opinions" id="twitch-thoughts">
    <%= form_with model: @opinion, url: opinion_index_path, method: :post do |f| %>
        <div class="field form-group" >
            <label class="text-info">twitch something</label>
            <br />
            <%= f.text_area :text, autofocus: true, class: "form-control op-text-area", placeholder: 'twitch your thoughts' %> 
        </div>
        <div class="actions d-flex flex-row justify-content-around">
            <%= f.submit "twitch" , class: "btn btn-info btn-md"%>
        </div>
    <% end %>
</div>

app/views/shared/_opinions-show.html.erb
<div class="opinions">
    
</div>

app/views/shared/_top-nav.html.erb
<nav class="top-nav d-flex flex-row justify-content-between align-items-center">
    <div class="logo ml-4">
        <i class="fab fa-twitter fa-2x"></i>
    </div>
    <div class="top-nav-left d-flex flex-row align-items-center mr-2">
        <%= link_to '#' do %>
            <i class="mr-4 fa fa-pen fa-2x"></i>
        <% end %>
        <%= link_to '#' do %>
            <i class="mr-4 fa fa-envelope fa-2x"></i>
        <% end %>
        <%= link_to '#' do %>
        <i class="mr-4 fa fa-search fa-2x"></i>
        <% end %>
        <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa fa-sign-out-alt fa-2x" aria-hidden="true"></i>
        <% end %> 
    </div>
</nav>